import { StatusBar } from 'expo-status-bar';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { Session } from '@supabase/supabase-js';
import { CreatorDashboard } from '@/components/CreatorDashboard'; import { COLORS, RADII, SPACING, TYPOGRAPHY } from '@/constants/theme'; import { supabase } from '@/services/supabase';
export default function App() {
  const [session,setSession]=useState<Session|null>(null); const [ready,setReady]=useState(false); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{ void supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true);}); const {data}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next)); return ()=>data.subscription.unsubscribe();},[]);
  async function signIn(){setBusy(true);setError('');const {error:authError}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(authError)setError(authError.message);setBusy(false);} async function signOut(){await supabase.auth.signOut();}
  return <SafeAreaView style={styles.safe}><StatusBar style="light" />{!ready?<View style={styles.center}><ActivityIndicator color={COLORS.gold}/></View>:session?<CreatorDashboard onSignOut={signOut}/>:<View style={styles.loginWrap}><View style={styles.loginCard}><Text style={styles.eyebrow}>CHC ARTISTS</Text><Text style={styles.title}>Create, manage, and submit to CHC</Text><Text style={styles.subtitle}>Music and Learn & Study creator dashboard</Text><TextInput style={styles.input} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor={COLORS.muted} value={email} onChangeText={setEmail}/><TextInput style={styles.input} secureTextEntry placeholder="Password" placeholderTextColor={COLORS.muted} value={password} onChangeText={setPassword} onSubmitEditing={signIn}/><Pressable style={[styles.button,(busy||!email||!password)&&styles.disabled]} disabled={busy||!email||!password} onPress={signIn}><Text style={styles.buttonText}>{busy?'Signing in…':'Sign in'}</Text></Pressable>{!!error&&<Text style={styles.error}>{error}</Text>}<Text style={styles.note}>Use an authorized CHC creator or admin account. Your submissions stay private until review and publication.</Text></View></View>}</SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.black},center:{flex:1,alignItems:'center',justifyContent:'center'},loginWrap:{flex:1,justifyContent:'center',alignItems:'center',padding:SPACING.lg,backgroundColor:COLORS.black},loginCard:{width:'100%',maxWidth:480,gap:SPACING.md,padding:SPACING.xl,borderRadius:RADII.lg,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface},eyebrow:{color:COLORS.gold,fontSize:12,fontWeight:'900',letterSpacing:2},title:{color:COLORS.white,fontFamily:TYPOGRAPHY.title,fontSize:32,lineHeight:40},subtitle:{color:COLORS.goldBright,fontWeight:'800',fontSize:16},input:{color:COLORS.white,backgroundColor:COLORS.black,borderWidth:1,borderColor:COLORS.border,borderRadius:RADII.sm,paddingHorizontal:14,paddingVertical:12},button:{backgroundColor:COLORS.gold,borderRadius:RADII.sm,paddingVertical:13,alignItems:'center'},disabled:{opacity:.45},buttonText:{color:COLORS.black,fontWeight:'900'},error:{color:'#FF8B8B'},note:{color:COLORS.muted,fontSize:12,lineHeight:18}});
