import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { creatorService } from '@/services/creatorService'; import { COLORS, RADII, SPACING, TYPOGRAPHY } from '@/constants/theme';
import type { CatalogOption, CreatorAccount, CreatorDraft, CreatorSubmission, UploadCandidate } from '@/types/creator'; import { LyricsStudio } from '@/components/LyricsStudio';
import { MediaPreview } from '@/components/MediaPreview'; import { ReviseSubmission } from '@/components/ReviseSubmission';
const emptyDraft = (): CreatorDraft => ({ mode: 'music', title: '', description: '', releaseType: 'single', artistId: '', cantorId: '', seasonId: '', hymnId: '', localizedTitle: { en: '', ar: '', cop: '', fr: '' }, media: [] });
function statusLabel(value: string) { return value.replaceAll('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase()); }
function Field({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (v: string) => void; multiline?: boolean }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} value={value} onChangeText={onChange} multiline={multiline} placeholderTextColor={COLORS.muted} /></View>; }
function Chips({ items, value, onChange }: { items: { id: string; title: string }[]; value: string; onChange: (v: string) => void }) { return <View style={styles.chips}>{items.map((x) => <Pressable key={x.id} onPress={() => onChange(x.id)} style={[styles.chip, value === x.id && styles.chipActive]}><Text style={[styles.chipText, value === x.id && styles.chipTextActive]}>{x.title}</Text></Pressable>)}</View>; }
export function CreatorDashboard({ onSignOut }: { onSignOut: () => void }) {
  const [accounts, setAccounts] = useState<CreatorAccount[]>([]); const [accountId, setAccountId] = useState(''); const [submissions, setSubmissions] = useState<CreatorSubmission[]>([]); const [artists, setArtists] = useState<CatalogOption[]>([]); const [cantors, setCantors] = useState<CatalogOption[]>([]); const [seasons, setSeasons] = useState<CatalogOption[]>([]); const [hymns, setHymns] = useState<CatalogOption[]>([]); const [tab, setTab] = useState<'home'|'create'|'lyrics'>('home'); const [draft, setDraft] = useState(emptyDraft()); const [busy, setBusy] = useState(false); const [newName, setNewName] = useState(''); const [previewId, setPreviewId] = useState<string|null>(null); const [revising, setRevising] = useState<CreatorSubmission|null>(null);
  const account = accounts.find((x) => x.id === accountId); const editable = useMemo(() => submissions.filter((x) => ['draft','uploading','ready_to_submit','changes_requested'].includes(x.status)), [submissions]);
  useEffect(() => { void creatorService.accounts().then((rows) => { setAccounts(rows); if (rows[0]) setAccountId(rows[0].id); }).catch((e) => Alert.alert('Unable to load creator access', creatorService.describeError(e))); }, []);
  useEffect(() => { if (!accountId) return; void Promise.all([creatorService.submissions(accountId), creatorService.artists(accountId), creatorService.cantors(accountId), creatorService.seasons(), creatorService.hymns()]).then(([s,a,c,se,h]) => { setSubmissions(s); setArtists(a); setCantors(c); setSeasons(se); setHymns(h); }); }, [accountId]);
  async function pick(mediaType: 'audio'|'video'|'image') { const result = await DocumentPicker.getDocumentAsync({ type: mediaType === 'audio' ? 'audio/*' : mediaType === 'video' ? 'video/*' : 'image/*', copyToCacheDirectory: true, multiple: mediaType !== 'image' }); if (result.canceled) return; const files: UploadCandidate[] = result.assets.map((x) => ({ id: `${Date.now()}-${x.name}`, name: x.name, uri: x.uri, mimeType: x.mimeType || `${mediaType}/*`, size: x.size || 0, mediaType, progress: 0 })); if (mediaType === 'image') setDraft((d) => ({ ...d, artwork: files[0] })); else setDraft((d) => ({ ...d, media: [...d.media, ...files] })); }
  function move(index: number, delta: number) { setDraft((d) => { const media = [...d.media]; const next = index + delta; if (next < 0 || next >= media.length) return d; [media[index], media[next]] = [media[next], media[index]]; return { ...d, media }; }); }
  async function createPerson(kind: 'artist'|'cantor') { if (!newName.trim() || !accountId) return; setBusy(true); try { const row = kind === 'artist' ? await creatorService.createArtist(accountId, newName) : await creatorService.createCantor(accountId, newName); if (kind === 'artist') setArtists((x) => [...x, row]); else setCantors((x) => [...x, row]); setNewName(''); } catch(e) { Alert.alert('Could not create', creatorService.describeError(e)); } finally { setBusy(false); } }
  async function submitDraft() { if (!accountId || !draft.title.trim() || !draft.media.length) return Alert.alert('Missing details', 'Add a title and at least one media file.'); if (draft.mode === 'music' && !draft.artistId) return Alert.alert('Artist required', 'Choose an artist for this release.'); if (draft.mode !== 'music' && !draft.cantorId) return Alert.alert('Cantor required', 'Choose a cantor.'); if (draft.mode === 'learning_lesson_set' && !draft.hymnId) return Alert.alert('Hymn required', 'Choose the hymn this lesson set teaches.'); setBusy(true);
    try { const type = draft.mode === 'music' ? 'music_release' : draft.mode; const submissionId = await creatorService.createSubmission(accountId, type, draft.title, draft.description); if (draft.mode === 'music') await creatorService.createRelease(accountId, draft.artistId, draft.releaseType, draft.title, draft.description, draft.localizedTitle); else await creatorService.createLearningShell(draft.mode === 'learning_album' ? 'album' : 'lesson_set', accountId, draft.cantorId, draft.seasonId, draft.hymnId, draft.title, draft.description, submissionId, draft.localizedTitle);
      const files = draft.artwork ? [draft.artwork, ...draft.media] : draft.media; const mediaRole = draft.mode === 'music' ? 'track' : 'lesson'; for (let i=0;i<files.length;i++) { const file = files[i]; const intent = await creatorService.upload(accountId, file, (progress) => setDraft((d) => ({ ...d, artwork: d.artwork?.id === file.id ? { ...d.artwork, progress } : d.artwork, media: d.media.map((m) => m.id === file.id ? { ...m, progress } : m) }))); await creatorService.attachUpload(submissionId, intent, file.name, i, file.id === draft.artwork?.id ? 'artwork' : mediaRole); }
      await creatorService.submit(submissionId); setDraft(emptyDraft()); setSubmissions(await creatorService.submissions(accountId)); setTab('home'); Alert.alert('Submitted', 'Your submission is now in CHC review.');
    } catch(e) { Alert.alert('Submission stopped', creatorService.describeError(e)); } finally { setBusy(false); }
  }
  if (revising) return <ReviseSubmission accountId={accountId} submission={revising} onClose={(changed) => { setRevising(null); if (changed) void creatorService.submissions(accountId).then(setSubmissions); }} />;
  if (tab === 'lyrics') return <LyricsStudio onSignOut={() => setTab('home')} />;
  return <View style={styles.root}><View style={styles.sidebar}><Text style={styles.brand}>CHC ARTISTS</Text><Text style={styles.account}>{account?.display_name || 'Creator Dashboard'}</Text><Pressable style={styles.nav} onPress={() => setTab('home')}><Text style={styles.navText}>Dashboard</Text></Pressable><Pressable style={styles.nav} onPress={() => setTab('create')}><Text style={styles.navText}>Create submission</Text></Pressable><Pressable style={styles.nav} onPress={() => setTab('lyrics')}><Text style={styles.navText}>Lyrics Studio</Text></Pressable><View style={{ flex: 1 }} /><Pressable onPress={onSignOut}><Text style={styles.muted}>Sign out</Text></Pressable></View>
    <ScrollView style={styles.main} contentContainerStyle={styles.content}>{accounts.length > 1 && <Chips items={accounts.map((x) => ({ id: x.id, title: x.display_name }))} value={accountId} onChange={setAccountId} />}{tab === 'home' ? <><Text style={styles.hero}>Creator dashboard</Text><Text style={styles.subhero}>Manage Music and Learn & Study submissions from draft through publication.</Text><View style={styles.stats}><View style={styles.stat}><Text style={styles.statNum}>{editable.length}</Text><Text style={styles.muted}>Editable</Text></View><View style={styles.stat}><Text style={styles.statNum}>{submissions.filter(x=>x.status==='pending_review').length}</Text><Text style={styles.muted}>In review</Text></View><View style={styles.stat}><Text style={styles.statNum}>{submissions.filter(x=>x.status==='published').length}</Text><Text style={styles.muted}>Published</Text></View></View><View style={styles.card}><Text style={styles.cardTitle}>Submissions</Text>{submissions.length ? submissions.map((s) => <View key={s.id} style={styles.row}><View style={{ flex:1 }}><Text style={styles.rowTitle}>{s.title}</Text><Text style={styles.muted}>{s.submission_type.replaceAll('_',' ')} • Updated {new Date(s.updated_at).toLocaleDateString()}</Text>{s.status === 'changes_requested' && s.review_notes ? <Text style={styles.warning}>Changes requested: {s.review_notes}</Text> : null}</View>{s.status === 'changes_requested' ? <Pressable onPress={() => setRevising(s)}><Text style={styles.link}>Address changes</Text></Pressable> : null}<View style={styles.status}><Text style={styles.statusText}>{statusLabel(s.status)}</Text></View></View>) : <Text style={styles.muted}>No submissions yet.</Text>}</View></> : <>
      <Text style={styles.hero}>New submission</Text><Chips items={[{id:'music',title:'Music release'},{id:'learning_album',title:'Learning album'},{id:'learning_lesson_set',title:'Lesson set'}]} value={draft.mode} onChange={(mode) => setDraft((d) => ({...d, mode: mode as CreatorDraft['mode']}))} />
      <View style={styles.card}><Text style={styles.cardTitle}>Metadata</Text><Field label="Title" value={draft.title} onChange={(title)=>setDraft(d=>({...d,title}))}/><Field label="Description" value={draft.description} onChange={(description)=>setDraft(d=>({...d,description}))} multiline />{draft.mode==='music' && <><Text style={styles.label}>Release type</Text><Chips items={[{id:'single',title:'Single'},{id:'ep',title:'EP'},{id:'album',title:'Album'}]} value={draft.releaseType} onChange={(releaseType)=>setDraft(d=>({...d,releaseType:releaseType as any}))}/><Text style={styles.label}>Artist</Text><Chips items={artists} value={draft.artistId} onChange={(artistId)=>setDraft(d=>({...d,artistId}))}/></>}{draft.mode!=='music' && <><Text style={styles.label}>Cantor</Text><Chips items={cantors} value={draft.cantorId} onChange={(cantorId)=>setDraft(d=>({...d,cantorId}))}/><Text style={styles.label}>Season</Text><Chips items={seasons} value={draft.seasonId} onChange={(seasonId)=>setDraft(d=>({...d,seasonId}))}/>{draft.mode==='learning_lesson_set' && <><Text style={styles.label}>Hymn</Text><Chips items={hymns} value={draft.hymnId} onChange={(hymnId)=>setDraft(d=>({...d,hymnId}))}/></>}</>}</View>
      <View style={styles.card}><Text style={styles.cardTitle}>Localized titles</Text>{(['en','ar','cop','fr'] as const).map((locale)=><Field key={locale} label={{en:'English',ar:'Arabic',cop:'Coptic',fr:'French'}[locale]} value={draft.localizedTitle[locale]} onChange={(value)=>setDraft(d=>({...d,localizedTitle:{...d.localizedTitle,[locale]:value}}))}/>)}</View>
      <View style={styles.card}><Text style={styles.cardTitle}>People</Text><Field label={`New ${draft.mode==='music'?'artist':'cantor'} name`} value={newName} onChange={setNewName}/><Pressable style={styles.secondary} disabled={busy} onPress={()=>void createPerson(draft.mode==='music'?'artist':'cantor')}><Text style={styles.secondaryText}>Create {draft.mode==='music'?'artist':'cantor'}</Text></Pressable></View>
      <View style={styles.card}><Text style={styles.cardTitle}>Artwork & media</Text><View style={styles.actions}><Pressable style={styles.secondary} onPress={()=>void pick('image')}><Text style={styles.secondaryText}>{draft.artwork?'Replace artwork':'Choose artwork'}</Text></Pressable><Pressable style={styles.secondary} onPress={()=>void pick(draft.mode==='learning_lesson_set'?'video':'audio')}><Text style={styles.secondaryText}>Add {draft.mode==='learning_lesson_set'?'video/audio':'audio'} files</Text></Pressable></View>{draft.artwork && <View><View style={styles.row}><Text style={[styles.muted,{flex:1}]}>Artwork: {draft.artwork.name} {Math.round(draft.artwork.progress*100)}%</Text><Pressable onPress={()=>setPreviewId(previewId===draft.artwork!.id?null:draft.artwork!.id)}><Text style={styles.link}>{previewId===draft.artwork.id?'Hide':'Preview'}</Text></Pressable></View>{previewId===draft.artwork.id?<MediaPreview file={draft.artwork} onClose={()=>setPreviewId(null)}/>:null}</View>}{draft.media.map((m,i)=><View key={m.id}><View style={styles.row}><View style={{flex:1}}><Text style={styles.rowTitle}>{i+1}. {m.name}</Text><Text style={styles.muted}>{(m.size/1024/1024).toFixed(1)} MB • {Math.round(m.progress*100)}%</Text></View><Pressable onPress={()=>move(i,-1)}><Text style={styles.order}>↑</Text></Pressable><Pressable onPress={()=>move(i,1)}><Text style={styles.order}>↓</Text></Pressable><Pressable onPress={()=>setPreviewId(previewId===m.id?null:m.id)}><Text style={styles.link}>{previewId===m.id?'Hide':'Preview'}</Text></Pressable><Pressable onPress={()=>setDraft(d=>({...d,media:d.media.filter(x=>x.id!==m.id)}))}><Text style={styles.remove}>Remove</Text></Pressable></View>{previewId===m.id?<MediaPreview file={m} onClose={()=>setPreviewId(null)}/>:null}</View>)}</View>
      <View style={styles.card}><Text style={styles.cardTitle}>Submission preview</Text><Text style={styles.previewTitle}>{draft.title || 'Untitled submission'}</Text><Text style={styles.muted}>{draft.mode.replaceAll('_',' ')} • {draft.media.length} media item{draft.media.length===1?'':'s'}</Text><Text style={styles.muted}>Uploads remain private until CHC review and publication.</Text><Pressable style={[styles.primary,busy&&styles.disabled]} disabled={busy} onPress={()=>void submitDraft()}><Text style={styles.primaryText}>{busy?'Uploading & submitting…':'Submit to CHC'}</Text></Pressable></View></>}</ScrollView></View>;
}
const styles=StyleSheet.create({root:{flex:1,flexDirection:'row',backgroundColor:COLORS.black},sidebar:{width:220,padding:SPACING.lg,gap:SPACING.md,backgroundColor:'#0b0c0e',borderRightWidth:1,borderRightColor:COLORS.border},brand:{color:COLORS.gold,fontWeight:'900',letterSpacing:2},account:{color:COLORS.white,fontFamily:TYPOGRAPHY.title,fontSize:20},nav:{paddingVertical:10},navText:{color:COLORS.white,fontWeight:'700'},main:{flex:1},content:{padding:SPACING.xl,gap:SPACING.lg,maxWidth:1100,width:'100%',alignSelf:'center'},hero:{color:COLORS.white,fontFamily:TYPOGRAPHY.title,fontSize:38},subhero:{color:COLORS.muted,fontSize:16},stats:{flexDirection:'row',gap:SPACING.md,flexWrap:'wrap'},stat:{minWidth:150,padding:SPACING.lg,borderRadius:RADII.md,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border},statNum:{color:COLORS.goldBright,fontSize:30,fontWeight:'900'},card:{padding:SPACING.lg,gap:SPACING.md,borderRadius:RADII.lg,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border},cardTitle:{color:COLORS.white,fontSize:18,fontWeight:'900'},field:{gap:6},label:{color:COLORS.muted,fontWeight:'700',fontSize:12,textTransform:'uppercase',letterSpacing:1},input:{color:COLORS.white,backgroundColor:COLORS.black,borderWidth:1,borderColor:COLORS.border,borderRadius:RADII.sm,padding:12},multiline:{minHeight:90,textAlignVertical:'top'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:12,paddingVertical:9,borderRadius:20,borderWidth:1,borderColor:COLORS.border},chipActive:{backgroundColor:COLORS.gold,borderColor:COLORS.gold},chipText:{color:COLORS.white,fontWeight:'700'},chipTextActive:{color:COLORS.black},row:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:12,borderTopWidth:1,borderTopColor:COLORS.border},rowTitle:{color:COLORS.white,fontWeight:'800'},muted:{color:COLORS.muted,fontSize:12},warning:{color:'#ffc36b',marginTop:5},status:{paddingHorizontal:10,paddingVertical:6,borderRadius:20,backgroundColor:'#19202a'},statusText:{color:COLORS.goldBright,fontSize:11,fontWeight:'800'},actions:{flexDirection:'row',gap:10,flexWrap:'wrap'},secondary:{padding:11,borderWidth:1,borderColor:COLORS.gold,borderRadius:RADII.sm,alignItems:'center'},secondaryText:{color:COLORS.goldBright,fontWeight:'800'},primary:{padding:14,borderRadius:RADII.sm,backgroundColor:COLORS.gold,alignItems:'center'},primaryText:{color:COLORS.black,fontWeight:'900'},disabled:{opacity:.5},order:{color:COLORS.goldBright,fontSize:20},remove:{color:'#ff8b8b',fontWeight:'700'},link:{color:COLORS.goldBright,fontWeight:'700'},previewTitle:{color:COLORS.white,fontFamily:TYPOGRAPHY.title,fontSize:24}});
